#!/bin/bash

# 定时关机
function shutdown() {
    date -d "$1" +"%Y-%m-%d %H:%M:%S"
    shutdown -h now
}

# 定时开机
function startup() {
    date -d "$1" +"%Y-%m-%d %H:%M:%S"
    systemctl start getty@tty1.service
}

# 获取当前时间
function currentTime() {
    date +"%Y-%m-%d %H:%M:%S"
}

# 检查参数
if [ $# -lt 1 ]; then
    echo "Usage: $0 <time>"
    exit 1
fi

# 判断是否是关机
if [ $1 = "shutdown" ]; then
    shutdown "$2"
elif [ $1 = "startup" ]; then
    startup "$2"
else
    echo "Invalid command."
    exit 1
fi
